In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU 
# SimpleRNN -> LSTM (계산이 너무 복잡) -> GRU (계산 간소화, LSTM 정도의 성능) 
from tensorflow.keras import Sequential

import pandas as pd

In [3]:
df = pd.read_csv('./data/sample.csv')

In [4]:
df

          date    x
0   2021-01-01    1
1   2021-01-02    2
2   2021-01-03    3
3   2021-01-04    4
4   2021-01-05    5
..         ...  ...
95  2021-04-06   96
96  2021-04-07   97
97  2021-04-08   98
98  2021-04-09   99
99  2021-04-10  100

[100 rows x 2 columns]

In [18]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [19]:
df['x'].values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [20]:
x_data, y_data = split_xy1(df['x'].values, 3)

In [21]:
x_data

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19, 20],
       [19, 20, 21],
       [20, 21, 22],
       [21, 22, 23],
       [22, 23, 24],
       [23, 24, 25],
       [24, 25, 26],
       [25, 26, 27],
       [26, 27, 28],
       [27, 28, 29],
       [28, 29, 30],
       [29, 30, 31],
       [30, 31, 32],
       [31, 32, 33],
       [32, 33, 34],
       [33, 34, 35],
       [34, 35, 36],
       [35, 36, 37],
       [36, 37, 38],
       [37, 38, 39],
       [38, 39, 40],
       [39, 40, 41],
       [40, 41, 42],
       [41, 42, 43],
       [42, 43, 44],
       [43, 44, 45],
       [44, 45, 46],
       [45, 46, 47],
       [46, 47, 48],
       [47, 48, 49],
       [48, 49, 50],
       [49, 50, 51],
       [50, 51, 52],
       [51, 52, 53],
       [52, 53, 54],
       [53, 54, 55],
       [54, 55, 56],
       [55, 56, 57],
       [56, 57, 58],
       [57, 58, 59],
       [58, 59, 60],
       [59, 60, 61],
       [60, 61, 62],
       [61, 62, 63],
       [62, 63, 64],
       [63, 64, 65],
       [64, 65, 66],
       [65, 66, 67],
       [66, 67, 68],
       [67, 68, 69],
       [68, 69, 70],
       [69, 70, 71],
       [70, 71, 72],
       [71, 72, 73],
       [72, 73, 74],
       [73, 74, 75],
       [74, 75, 76],
       [75, 76, 77],
       [76, 77, 78],
       [77, 78, 79],
       [78, 79, 80],
       [79, 80, 81],
       [80, 81, 82],
       [81, 82, 83],
       [82, 83, 84],
       [83, 84, 85],
       [84, 85, 86],
       [85, 86, 87],
       [86, 87, 88],
       [87, 88, 89],
       [88, 89, 90],
       [89, 90, 91],
       [90, 91, 92],
       [91, 92, 93],
       [92, 93, 94],
       [93, 94, 95],
       [94, 95, 96],
       [95, 96, 97],
       [96, 97, 98],
       [97, 98, 99]], dtype=int64)

In [22]:
y_data

array([  4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100], dtype=int64)

In [23]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 추가
        # if end_number > len(dataset) -1:
        # break
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [25]:
x_data, y_data = split_xy2(df['x'].values, 3, 2)

In [26]:
x_data

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19, 20],
       [19, 20, 21],
       [20, 21, 22],
       [21, 22, 23],
       [22, 23, 24],
       [23, 24, 25],
       [24, 25, 26],
       [25, 26, 27],
       [26, 27, 28],
       [27, 28, 29],
       [28, 29, 30],
       [29, 30, 31],
       [30, 31, 32],
       [31, 32, 33],
       [32, 33, 34],
       [33, 34, 35],
       [34, 35, 36],
       [35, 36, 37],
       [36, 37, 38],
       [37, 38, 39],
       [38, 39, 40],
       [39, 40, 41],
       [40, 41, 42],
       [41, 42, 43],
       [42, 43, 44],
       [43, 44, 45],
       [44, 45, 46],
       [45, 46, 47],
       [46, 47, 48],
       [47, 48, 49],
       [48, 49, 50],
       [49, 50, 51],
       [50, 51, 52],
       [51, 52, 53],
       [52, 53, 54],
       [53, 54, 55],
       [54, 55, 56],
       [55, 56, 57],
       [56, 57, 58],
       [57, 58, 59],
       [58, 59, 60],
       [59, 60, 61],
       [60, 61, 62],
       [61, 62, 63],
       [62, 63, 64],
       [63, 64, 65],
       [64, 65, 66],
       [65, 66, 67],
       [66, 67, 68],
       [67, 68, 69],
       [68, 69, 70],
       [69, 70, 71],
       [70, 71, 72],
       [71, 72, 73],
       [72, 73, 74],
       [73, 74, 75],
       [74, 75, 76],
       [75, 76, 77],
       [76, 77, 78],
       [77, 78, 79],
       [78, 79, 80],
       [79, 80, 81],
       [80, 81, 82],
       [81, 82, 83],
       [82, 83, 84],
       [83, 84, 85],
       [84, 85, 86],
       [85, 86, 87],
       [86, 87, 88],
       [87, 88, 89],
       [88, 89, 90],
       [89, 90, 91],
       [90, 91, 92],
       [91, 92, 93],
       [92, 93, 94],
       [93, 94, 95],
       [94, 95, 96],
       [95, 96, 97],
       [96, 97, 98]], dtype=int64)

In [27]:
y_data

array([[  4,   5],
       [  5,   6],
       [  6,   7],
       [  7,   8],
       [  8,   9],
       [  9,  10],
       [ 10,  11],
       [ 11,  12],
       [ 12,  13],
       [ 13,  14],
       [ 14,  15],
       [ 15,  16],
       [ 16,  17],
       [ 17,  18],
       [ 18,  19],
       [ 19,  20],
       [ 20,  21],
       [ 21,  22],
       [ 22,  23],
       [ 23,  24],
       [ 24,  25],
       [ 25,  26],
       [ 26,  27],
       [ 27,  28],
       [ 28,  29],
       [ 29,  30],
       [ 30,  31],
       [ 31,  32],
       [ 32,  33],
       [ 33,  34],
       [ 34,  35],
       [ 35,  36],
       [ 36,  37],
       [ 37,  38],
       [ 38,  39],
       [ 39,  40],
       [ 40,  41],
       [ 41,  42],
       [ 42,  43],
       [ 43,  44],
       [ 44,  45],
       [ 45,  46],
       [ 46,  47],
       [ 47,  48],
       [ 48,  49],
       [ 49,  50],
       [ 50,  51],
       [ 51,  52],
       [ 52,  53],
       [ 53,  54],
       [ 54,  55],
       [ 55,  56],
       [ 56,  57],
       [ 57,  58],
       [ 58,  59],
       [ 59,  60],
       [ 60,  61],
       [ 61,  62],
       [ 62,  63],
       [ 63,  64],
       [ 64,  65],
       [ 65,  66],
       [ 66,  67],
       [ 67,  68],
       [ 68,  69],
       [ 69,  70],
       [ 70,  71],
       [ 71,  72],
       [ 72,  73],
       [ 73,  74],
       [ 74,  75],
       [ 75,  76],
       [ 76,  77],
       [ 77,  78],
       [ 78,  79],
       [ 79,  80],
       [ 80,  81],
       [ 81,  82],
       [ 82,  83],
       [ 83,  84],
       [ 84,  85],
       [ 85,  86],
       [ 86,  87],
       [ 87,  88],
       [ 88,  89],
       [ 89,  90],
       [ 90,  91],
       [ 91,  92],
       [ 92,  93],
       [ 93,  94],
       [ 94,  95],
       [ 95,  96],
       [ 96,  97],
       [ 97,  98],
       [ 98,  99],
       [ 99, 100]], dtype=int64)

In [28]:
def make_dataset(data, label, window_size=20):
    feature_list = []
    label_list = []
    for i in range(len(data) - window_size):
        feature_list.append(np.array(data.iloc[i:i+window_size]))
        label_list.append(np.array(label.iloc[i+window_size]))
    return np.array(feature_list), np.array(label_list)

In [29]:
y_data

array([[  4,   5],
       [  5,   6],
       [  6,   7],
       [  7,   8],
       [  8,   9],
       [  9,  10],
       [ 10,  11],
       [ 11,  12],
       [ 12,  13],
       [ 13,  14],
       [ 14,  15],
       [ 15,  16],
       [ 16,  17],
       [ 17,  18],
       [ 18,  19],
       [ 19,  20],
       [ 20,  21],
       [ 21,  22],
       [ 22,  23],
       [ 23,  24],
       [ 24,  25],
       [ 25,  26],
       [ 26,  27],
       [ 27,  28],
       [ 28,  29],
       [ 29,  30],
       [ 30,  31],
       [ 31,  32],
       [ 32,  33],
       [ 33,  34],
       [ 34,  35],
       [ 35,  36],
       [ 36,  37],
       [ 37,  38],
       [ 38,  39],
       [ 39,  40],
       [ 40,  41],
       [ 41,  42],
       [ 42,  43],
       [ 43,  44],
       [ 44,  45],
       [ 45,  46],
       [ 46,  47],
       [ 47,  48],
       [ 48,  49],
       [ 49,  50],
       [ 50,  51],
       [ 51,  52],
       [ 52,  53],
       [ 53,  54],
       [ 54,  55],
       [ 55,  56],
       [ 56,  57],
       [ 57,  58],
       [ 58,  59],
       [ 59,  60],
       [ 60,  61],
       [ 61,  62],
       [ 62,  63],
       [ 63,  64],
       [ 64,  65],
       [ 65,  66],
       [ 66,  67],
       [ 67,  68],
       [ 68,  69],
       [ 69,  70],
       [ 70,  71],
       [ 71,  72],
       [ 72,  73],
       [ 73,  74],
       [ 74,  75],
       [ 75,  76],
       [ 76,  77],
       [ 77,  78],
       [ 78,  79],
       [ 79,  80],
       [ 80,  81],
       [ 81,  82],
       [ 82,  83],
       [ 83,  84],
       [ 84,  85],
       [ 85,  86],
       [ 86,  87],
       [ 87,  88],
       [ 88,  89],
       [ 89,  90],
       [ 90,  91],
       [ 91,  92],
       [ 92,  93],
       [ 93,  94],
       [ 94,  95],
       [ 95,  96],
       [ 96,  97],
       [ 97,  98],
       [ 98,  99],
       [ 99, 100]], dtype=int64)